# Generated by packaging/bump.sh on each release — do not edit by hand.
# Install via a tap:  brew install MarcosSmeets/tap/vader
#   (create github.com/MarcosSmeets/homebrew-tap with this file under Formula/)
class Vader < Formula
  desc "The Vader programming language compiler"
  homepage "https://github.com/MarcosSmeets/vader-langue"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/MarcosSmeets/vader-langue/releases/download/v0.4.0/vader-macos-arm64"
      sha256 "6f33a722c110c2547c078dab42897492ceb0a6c33c07e9faa342d8cbf4731ce8"
    end
    on_intel do
      url "https://github.com/MarcosSmeets/vader-langue/releases/download/v0.4.0/vader-macos-x86_64"
      sha256 "ee99e66b6618562e5565f731d633e41d3cabceaca238523bbecbb05a80a843f2"
    end
  end

  on_linux do
    url "https://github.com/MarcosSmeets/vader-langue/releases/download/v0.4.0/vader-linux-x86_64"
    sha256 "b43eee35f482547d8052753b2dde90ac7ced3e90fb7dd6b61af452fa8805b3d3"
  end

  def install
    bin.install Dir["vader*"].first => "vader"
  end

  test do
    assert_match "vader", shell_output("#{bin}/vader version")
  end
end
