# Generated by packaging/bump.sh on each release — do not edit by hand.
# Install via a tap:  brew install MarcosSmeets/tap/vader
#   (create github.com/MarcosSmeets/homebrew-tap with this file under Formula/)
class Vader < Formula
  desc "The Vader programming language compiler"
  homepage "https://github.com/MarcosSmeets/vader-langue"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/MarcosSmeets/vader-langue/releases/download/v1.0.0/vader-macos-arm64"
      sha256 "63b1630d4268463168d01338b61897fca0a1c1bba3c65f5407c88f50c8369373"
    end
    on_intel do
      url "https://github.com/MarcosSmeets/vader-langue/releases/download/v1.0.0/vader-macos-x86_64"
      sha256 "bf9afa5cbf4a8965d08ae907abea5d0abed77bf84cff823fd0b508b4ffa47ef4"
    end
  end

  on_linux do
    url "https://github.com/MarcosSmeets/vader-langue/releases/download/v1.0.0/vader-linux-x86_64"
    sha256 "b75980685b7ec9847b27fd96759b8d73fb34a4f563a61360844f3534bccee796"
  end

  def install
    bin.install Dir["vader*"].first => "vader"
  end

  test do
    assert_match "vader", shell_output("#{bin}/vader version")
  end
end
