#!/bin/sh
# Regenerates the Homebrew formula and winget manifests for a release.
# Run by the release workflow (and usable by hand). The SHA-256 sums come from env.
#
#   SHA_LINUX=... SHA_MACOS_X64=... SHA_MACOS_ARM64=... SHA_WIN=... \
#     sh packaging/bump.sh <version>      # version without the leading 'v', e.g. 0.4.0
set -eu

VER="${1:?usage: bump.sh <version>}"
: "${SHA_LINUX:?missing SHA_LINUX}"
: "${SHA_MACOS_X64:?missing SHA_MACOS_X64}"
: "${SHA_MACOS_ARM64:?missing SHA_MACOS_ARM64}"
: "${SHA_WIN:?missing SHA_WIN}"

REPO="MarcosSmeets/vader-langue"
BASE="https://github.com/$REPO/releases/download/v$VER"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WIN_UP="$(printf '%s' "$SHA_WIN" | tr '[:lower:]' '[:upper:]')"

# --- Homebrew formula ---
cat > "$ROOT/packaging/homebrew/vader.rb" <<EOF
# Generated by packaging/bump.sh on each release — do not edit by hand.
# Install via a tap:  brew install MarcosSmeets/tap/vader
#   (create github.com/MarcosSmeets/homebrew-tap with this file under Formula/)
class Vader < Formula
  desc "The Vader programming language compiler"
  homepage "https://github.com/$REPO"
  version "$VER"
  license "MIT"

  on_macos do
    on_arm do
      url "$BASE/vader-macos-arm64"
      sha256 "$SHA_MACOS_ARM64"
    end
    on_intel do
      url "$BASE/vader-macos-x86_64"
      sha256 "$SHA_MACOS_X64"
    end
  end

  on_linux do
    url "$BASE/vader-linux-x86_64"
    sha256 "$SHA_LINUX"
  end

  def install
    bin.install Dir["vader*"].first => "vader"
  end

  test do
    assert_match "vader", shell_output("#{bin}/vader version")
  end
end
EOF

# --- winget manifests (one versioned folder per release) ---
DIR="$ROOT/packaging/winget/manifests/m/Marco/Vader/$VER"
mkdir -p "$DIR"

cat > "$DIR/Marco.Vader.yaml" <<EOF
PackageIdentifier: Marco.Vader
PackageVersion: $VER
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
EOF

cat > "$DIR/Marco.Vader.installer.yaml" <<EOF
PackageIdentifier: Marco.Vader
PackageVersion: $VER
InstallerType: portable
Commands:
  - vader
Installers:
  - Architecture: x64
    InstallerUrl: $BASE/vader-windows-x86_64.exe
    InstallerSha256: $WIN_UP
ManifestType: installer
ManifestVersion: 1.6.0
EOF

cat > "$DIR/Marco.Vader.locale.en-US.yaml" <<EOF
PackageIdentifier: Marco.Vader
PackageVersion: $VER
PackageLocale: en-US
Publisher: Marcos Smeets
PublisherUrl: https://github.com/MarcosSmeets
PackageName: Vader
PackageUrl: https://github.com/$REPO
License: MIT
LicenseUrl: https://github.com/$REPO/blob/main/LICENSE
ShortDescription: The Vader programming language compiler.
Description: >-
  Vader is a compiled, statically-typed language with an opinionated toolchain
  (Clean Architecture + TDD scaffolding, native LLVM backend, built-in HTTP/JSON/DB).
Tags:
  - programming-language
  - compiler
  - vader
  - llvm
ManifestType: defaultLocale
ManifestVersion: 1.6.0
EOF

echo "bumped packaging to v$VER (homebrew + winget)"
